@echo off

REM Remove files generated by compiler in this directory and all subdirectories.
REM Compiled *.hex file is kept.

echo Removing "*.cof" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.cof"') do del "%%i" /f /q
echo.

echo Removing "*.d" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.d"') do del "%%i" /f /q
echo.

echo Removing "*.elf" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.elf"') do del "%%i" /f /q
echo.

echo Removing "*.o" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.o"') do del "%%i" /f /q
echo.

echo Removing "*.map" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.map"') do del "%%i" /f /q
echo.

echo Removing "*.mcs" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.mcs"') do del "%%i" /f /q
echo.

echo Removing "obj" directory...
rd "%~p0obj" /s /q
echo.

echo "%~n0.bat" done.